import { Footer } from '@/components/layouts/footer'
import { Header } from '@/components/layouts/header'
import type { Metadata } from 'next'
import { Exo_2 } from 'next/font/google'
import './globals.css'

const exo_2 = Exo_2({
	variable: '--font-exo_2',
	subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
	title: 'Homex',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${exo_2.variable} antialiased`}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
