import { Footer } from '@/components/layouts/footer'
import { Header } from '@/components/layouts/header'
import { QueryProvider } from '@/providers/queryClientProvider'
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { Exo_2 } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import './globals.css'

const exo_2 = Exo_2({
	variable: '--font-exo_2',
	subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
	title: 'Homex',
	description: 'Generated by create next app'
}

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	const messages = await getMessages()

	return (
		<html lang="en">
			<body className={`${exo_2.variable} antialiased`}>
				<NextIntlClientProvider messages={messages}>
					<QueryProvider>
						<Header />
						{children}
						<Footer />
						<ToastContainer theme="colored" />
					</QueryProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
